### ISSUE TITLE
posix_memalign

### ISSUE THREAD

**Issue by mdcb** [wavesoft/nanomsg-transport-ofi#1]
In nn_sofi_init, the argument to posix_memalign should be the address of the ingress pointer, not the pointer itself. Patch below.

```
--- a/src/transports/ofi/sofi.c
+++ b/src/transports/ofi/sofi.c
@@ -1212,7 +1212,7 @@ int nn_sofi_init ( struct nn_sofi *self, struct ofi_domain *domain, int offset,
     /* Allocate ingress buffers */
 #if _POSIX_C_SOURCE >= 200112L
     self->ingress_buffers = NULL;
-    ret = posix_memalign( (void**)self->ingress_buffers, sysconf(_SC_PAGESIZE), 
+    ret = posix_memalign( (void**) &self->ingress_buffers, sysconf(_SC_PAGESIZE), 
         ibufsz * rx_queue );
```

**Comment by wavesoft** [comment]
Hey @mdcb, Thanks for noticing this! 
Is this on the `devel-ofiw` branch? I am currently working on this part. I guess I didn't got any warning because I am developing on mac.

**Comment by mdcb** [comment]
Hi @wavesoft,
gdb'd through the demo and sent this, just to find your commit 2h ago ... I'll retry later.
I'm x86_64 / linux. Might have a few more questions as I go through the new transport. Are you content to use github issues for that, any other ways would be fine.

**Comment by wavesoft** [comment]
Sure @mdcb , thanks for your feedback. Github issues are fine. Just be aware that I am undergoing some major re-designs on the way I handle ingress buffers in sofi.

**Comment by mdcb** [comment]
Hi @wavesoft,
If you need beta testers, I'd be happy to help. Here I have a mini cluster with Mellanox ConnectX2 (but libfabric makes it all transparent of course). Your project is of particular interest.
Out of curiosity, are you or anyone at CERN doing something similar with 0MQ?

**Comment by wavesoft** [comment]
>  If you need beta testers, I'd be happy to help. Here I have a mini cluster with Mellanox ConnectX2 (but libfabric makes it all transparent of course). Your project is of particular interest.

I am definitely looking for beta testers (and possibly a second pair of eyes on the code) so if you are interested feel free to try it in your test case!

My latest commit to [`devel-ofiw`](https://github.com/wavesoft/nanomsg-transport-ofi/tree/devel-ofiw) has fixed a lot of stability and performance issues, but be aware that it's still in a very active development phase. I might even need to re-design some parts in order to fix some of the bugs that I observe.

>  Out of curiosity, are you or anyone at CERN doing something similar with 0MQ?

We are also working on a 0MQ implementation, however it's a bit trickier since 0MQ is more tightly bound to file descriptors and libfabric does not (always) play well with them. Also, before we switch to 0MQ I would like to make sure the nanomsg implementation is stable, since libfabric can behave unexpectedly in some cases.

If you are concerned about performance penalties of nanomsg compared to 0MQ i would suggest to first give the `ofi` transport a spin, using [my version of nanomsg](https://github.com/wavesoft/nanomsg/tree/pull-nn_allocmsg_ptr) (until my modifications are available on upstream) and the `nn_allocmsg_ptr` method to allocate zero-copy messages from existing data (as explained on [my pull request here](https://github.com/nanomsg/nanomsg/pull/612)).

**Comment by mdcb** [comment]
just fyi. - current tip of devel-ofiw gets stuck on the 'pull' side when the client disconnect. trace and backtrace below.
This might also be relevant: I recall seeing some slides saying you're using connectX3, probably the libfabric verb provider? Here I tried --enable-wait-sets to see what happens, turns out fi_wait_open is not supported in the current verb/libfabric - so that might be an issue to consider for you too.

https://github.com/ofiwg/libfabric/blob/master/prov/verbs/src/verbs_domain.c#L311

```
nanocat --pull --bind ofi://172.16.40.11:35000 -A
[0000171746.186384067] OFI[A]: Looking fabric for node=172.16.40.11, service=35000, fabric=(null), provider=(null)
OFI[H]: Using fabric=IB-0x80fe, provider=verbs
[0000171746.190315962] OFI[w]: Allocated new worker 0x1ac0c10
[0000171746.190325722] OFI[B]: nn_bofi_handler state=1, src=-2, type=-2
[0000171746.190524925] OFI[w]: Added EQ fd=0x1ac1270 on worker=0x1ac0c10
[0000171746.190532411] OFI[B]: We are listening for connections
[0000171749.608614194] OFI[w]: Got EQ Event from src=268439556, worker=0x1ac0c10, fd=0x1ac1270, event=1
[0000171749.608626028] OFI[B]: nn_bofi_handler state=2, src=268439556, type=1
[0000171749.608633922] OFI[B]: Got connection request
[0000171749.608637270] OFI[B]: Allocating new SOFI
[0000171749.608642751] OFI[B]: Initializing SOFI
[0000171749.608653511] OFI[w]: Allocated new worker 0x7f3b480008c0
[0000171749.608661330] OFI[S]: Options: Tx-Queue-Size: 16, Rx-Queue-Size: 16, Offset: 0
[0000171749.608666332] OFI[S]:          Max-Recv-Size: 131072 b, Slab-Size: 4096 b
[0000171749.608838569] OFI[S]:          Effective-Recv-Size: 131072 b
[0000171749.608856865] OFI[S]: Allocated page-aligned egress aux sz=2162688, at=0x7f3b4de7f000
[0000171749.609607721] OFI[B]: Starting SOFI in accept state
[0000171749.609651751] OFI[w]: Added EQ fd=0x7f3b48014370 on worker=0x7f3b480008c0
[0000171749.610739174] OFI[S]: Starting Accepted FSM 
[0000171749.610758220] OFI[S]: nn_sofi_handler state=1001, src=-2, type=-2
[0000171749.610767877] OFI[S]: FSM started, waiting for connection
[0000171749.610776371] OFI[w]: Removed fd=0x1ac1270 from worker=0x1ac0c10
[0000171749.611062411] OFI[w]: Added EQ fd=0x7f3b48018fb0 on worker=0x1ac0c10
[0000171749.611077738] OFI[B]: We are listening for connections
[0000171749.611097044] OFI[w]: Got EQ Event from src=268436557, worker=0x7f3b480008c0, fd=0x7f3b48014370, event=2
[0000171749.611107069] OFI[S]: nn_sofi_handler state=1002, src=268436557, type=2
[0000171749.611121902] OFI[S]: Endpoint connected, starting pipebase
[0000171749.611129115] OFI[S]: Starting keepalive timer
[0000171749.611135307] OFI[S]: Posting ingress buffer=0x7f3b4de7f000 (chunk=0x7f3b4de80000)
[0000171749.611164881] OFI[S]: CQ Event len=5, buf=0x7f3b4de7f000
[0000171749.611175272] OFI[S]: Posting another ingress buffer
[0000171749.611179587] OFI[S]: Posting ingress buffer=0x7f3b4dea0000 (chunk=0x7f3b4dea1000)
[0000171749.611184547] OFI[S]: Received BODY[5]
[0000171749.611189530] OFI[S]: NanoMsg RECV event
[0000171749.611193124] OFI[S]: Passing to nanomsg ingress buffer=0x7f3b4de7f000 (chunk=0x7f3b4de80000)
Hello
[0000171749.611209121] OFI[S]: User released buf=0x7f3b4de7f000
[0000171749.611385625] OFI[w]: Got EQ Event from src=268436557, worker=0x7f3b480008c0, fd=0x7f3b48014370, event=3
```

```
Thread 3 (Thread 0x7fcda58ad700 (LWP 15018)):
#0  0x00007fcda6767043 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fcda72c2a24 in nn_poller_wait (self=self@entry=0x7fcda74fa9a4 <self+132>, timeout=-1) at src/aio/poller_epoll.inc:176
#2  0x00007fcda72c51a1 in nn_worker_routine (arg=0x7fcda74fa960 <self+64>) at src/aio/worker_posix.inc:176
#3  0x00007fcda72c78dd in nn_thread_main_routine (arg=<optimized out>) at src/utils/thread_posix.inc:35
#4  0x00007fcda6a2c60a in start_thread (arg=0x7fcda58ad700) at pthread_create.c:334
#5  0x00007fcda6766a4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
Thread 2 (Thread 0x7fcda4ea3700 (LWP 15019)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007fcda6a2e9cd in __GI___pthread_mutex_lock (mutex=0x209ad28) at ../nptl/pthread_mutex_lock.c:81
#2  0x00007fcda72c721b in nn_mutex_lock (self=<optimized out>) at src/utils/mutex.c:70
#3  0x00007fcda72c2285 in nn_ctx_enter (self=<optimized out>) at src/aio/ctx.c:48
#4  0x00007fcda72e2d9f in nn_ofiw_polling_thread (data=0x209b1e8) at src/transports/ofi/ofiw_unithread.inc:358
#5  0x00007fcda72c78dd in nn_thread_main_routine (arg=<optimized out>) at src/utils/thread_posix.inc:35
#6  0x00007fcda6a2c60a in start_thread (arg=0x7fcda4ea3700) at pthread_create.c:334
#7  0x00007fcda6766a4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
Thread 1 (Thread 0x7fcda7708740 (LWP 15017)):
#0  0x00007fcda675afdd in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fcda70777d2 in poll (__timeout=-1, __nfds=2, __fds=0x7fff79ba2f90) at /usr/include/bits/poll2.h:46
#2  fi_ibv_poll_events (timeout=-1, _cq=0x7fcda0014610) at prov/verbs/src/fi_verbs.c:2859
#3  fi_ibv_cq_sread (cq=0x7fcda0014610, buf=0x7fff79ba3000, count=1, cond=<optimized out>, timeout=-1) at prov/verbs/src/fi_verbs.c:2929
#4  0x00007fcda72de2bb in fi_cq_sread (timeout=-1, cond=0x0, count=1, buf=0x7fff79ba3000, cq=<optimized out>) at /usr/include/rdma/fi_eq.h:382
#5  nn_sofi_recv (pb=0x7fcda0001050, msg=0x7fff79ba3540) at src/transports/ofi/sofi.c:1263
#6  0x00007fcda72bfe5a in nn_pipe_recv (self=self@entry=0x7fcda0001050, msg=msg@entry=0x7fff79ba3540) at src/core/pipe.c:207
#7  0x00007fcda72cda8b in nn_fq_recv (self=0x209af20, msg=0x7fff79ba3540, pipe=pipe@entry=0x0) at src/protocols/utils/fq.c:72
#8  0x00007fcda72c81af in nn_xpull_recv (self=<optimized out>, msg=<optimized out>) at src/protocols/pipeline/xpull.c:162
#9  0x00007fcda72c1937 in nn_sock_recv (self=0x209acb0, msg=msg@entry=0x7fff79ba3540, flags=flags@entry=0) at src/core/sock.c:727
#10 0x00007fcda72bf2d7 in nn_recvmsg (s=s@entry=0, msghdr=msghdr@entry=0x7fff79ba35f0, flags=flags@entry=0) at src/core/global.c:870
#11 0x00007fcda72bf608 in nn_recv (s=s@entry=0, buf=buf@entry=0x7fff79ba3628, len=len@entry=18446744073709551615, flags=flags@entry=0) at src/core/global.c:693
#12 0x0000000000401c9e in nn_recv_loop (options=options@entry=0x7fff79ba3650, sock=sock@entry=0) at tools/nanocat.c:507
#13 0x00000000004013e2 in main (argc=<optimized out>, argv=<optimized out>) at tools/nanocat.c:627
```

--enale-wait-set

```
nanocat --pull --bind ofi://172.16.40.11:35000 -A
[0000172269.448667869] OFI[A]: Looking fabric for node=172.16.40.11, service=35000, fabric=(null), provider=(null)
OFI[H]: Using fabric=IB-0x80fe, provider=verbs
OFI: Error on fi_wait_open(): src/transports/ofi/ofiw_unithread.inc:451, ret=-38 (Function not implemented)
OFI: Error on nn_ofiw_pool_init(): src/transports/ofi/ofiapi.c:280, ret=-38 (Function not implemented)
Can't bind: Function not implemented
```
